### ISSUE TITLE
installation failure due to echoconda

### ISSUE THREAD

**Issue by huanyaogao** [RajLabMSSM/catalogueR#10]
Thank you for developing the package!
I was trying to install_github the package from dev branch, and encountered two problems.
1. catalogueR installation encountered the following error and was not able to complete:

Error: object ‘find_package’ is not exported by 'namespace:echoconda'
Execution halted
(I think the function should be find_packages() instead)

2. This may be not of your priority, but when I first tried to install on windows-based system, the dependent echoconda can't be installed at all because of the following error:

Warning in system("sh ./configure.win") : 'sh' not found
ERROR: configuration failed for package 'echoconda'

This can be avoided by using Linux bases system, but it would be nice if it can be used on windows R as well. 

Thank you so much!

**Comment by huanyaogao** [comment]
Hi,  
I think I have figured out what happened in the first error above.
The NAMESPACE in catalogueR@dev was trying to export echoconda::find_package() and echotabix::query_tabular(), both of which seemed to have retired or renamed in the current version. Fix the function name in NAMESPACE will fix this error. Once fixed, there might be potential conflicts when the old versions of echoconda and echotabix were combined with new version of catalogueR though, please double check.
Thanks.

**Comment by bschilder** [comment]
Hi @huanyaogao, yes the _dev_ version wasn't quite ready for release given some of the latest changes with the _echoverse_. However I just overhauled the `catalogueR` package to make it compatible with the latest version of these other packages. 

All updates are now merged into the _master_ branch, so please install from there.

**Comment by huanyaogao** [comment]
Thank you so much for the update!

**Comment by bschilder** [comment]
No problem! Let me know if everything works ok for you
