### ISSUE TITLE
Updates in the eQTL Catalogue

### ISSUE THREAD

**Issue by kauralasoo** [RajLabMSSM/catalogueR#3]
Hi Brian,

I wanted to let you know about few changes that we have made to eQTL Catalogue that might also influence how catalogueR works:
1. In the release 3 of eQTL Catalogue we had and issue where AC and AN fields were accidentally swapped in the summary statistics files. Since the AN field is commonly used to infer sample size then this might have some influence on the colocalisation performance. This should not lead to false positives, but might have reduced the power to detect colocaliations in some instances.
2. The column order of the tabix-indexed files has now changed and unfortunately it is no longer consistent between the uniformly processed files and imported GTEx_v8 files. It is still consistent within all of the uniformly processed files. Sorry about that! Going forward, I think it is probably safer to also fetch the first row to make sure that the column names are correct. 
3. We recently discovered the seqminer R package and have now switched to that in our colocalisation tutorial:
http://htmlpreview.github.io/?https://github.com/kauralasoo/eQTL-Catalogue-resources/blob/master/tutorials/tabix_use_case.html
We haven't done a lot of testing yet, but it seems to be more stable that using Rsamtools and does not require systems requests to tabix command-line tool. It is also a lot cleaner.

Best,
Kaur

**Comment by bschilder** [comment]
Hi Kaur, 

Thanks for much for all these updates! Apologies for the super long delay, I just realized that GitHub wasn't sending me notifications for this repo.

1. Good to know, thanks!
2. I actually made some updates recently that address this using the strategy you outlined.
3. I hadn't heard of this one! I'll have to give it a try. Might be worth rewriting the tabix portions of catalogueR to include this.

Thanks again, 
Brian
